swagger: "2.0"
info:
  version: 1.0
  title: Toolbox API - DEPRECATED
  description: API for toolbox project, <a href='/swagger.yaml'>download swagger.yaml</a>
  termsOfService: ''
  contact:
    name: ''
    url: ''
    email: ''
  license:
    name: ''
    url: ''
paths:
  /api/v0.1/Apps:
    get:
      tags:
      - Apps
      operationId: GetAsync
      consumes: []
      produces:
      - application/json
      parameters: []
      responses:
        200:
          description: Success
          schema:
            uniqueItems: false
            type: array
            items:
              $ref: '#/definitions/Item'
definitions:
  Item:
    type: object
    properties: {}

