swagger: "2.0"
info:
  version: 1.0
  title: Toolbox API
  description: API for toolbox project, , <a href='/swagger.yaml'>download swagger.yaml</a>
  termsOfService: ''
  contact:
    name: ''
    url: ''
    email: ''
  license:
    name: RESG/GTS/DWS/
    url: ''
paths:
  /api/v1/Apps:
    get:
      tags:
      - Apps
      operationId: Get
      consumes: []
      produces:
      - application/json
      parameters: []
      responses:
        200:
          description: Success
          schema:
            uniqueItems: false
            type: array
            items:
              $ref: '#/definitions/Item'
  /api/Values:
    get:
      tags:
      - Values
      operationId: Get
      consumes: []
      produces:
      - text/plain
      - application/json
      - text/json
      parameters:
      - name: api-version
        in: query
        description: The requested API version
        type: string
      responses:
        200:
          description: Success
          schema:
            uniqueItems: false
            type: array
            items:
              type: string
    post:
      tags:
      - Values
      operationId: Post
      consumes:
      - application/json-patch+json
      - application/json
      - text/json
      - application/*+json
      produces: []
      parameters:
      - name: value
        in: body
        schema:
          type: string
      - name: api-version
        in: query
        description: The requested API version
        type: string
      responses:
        200:
          description: Success
  /api/Values/{id}:
    get:
      tags:
      - Values
      operationId: Get
      consumes: []
      produces:
      - text/plain
      - application/json
      - text/json
      parameters:
      - name: id
        in: path
        required: true
        type: integer
        format: int32
      - name: api-version
        in: query
        description: The requested API version
        type: string
      responses:
        200:
          description: Success
          schema:
            type: string
    put:
      tags:
      - Values
      operationId: Put
      consumes:
      - application/json-patch+json
      - application/json
      - text/json
      - application/*+json
      produces: []
      parameters:
      - name: id
        in: path
        required: true
        type: integer
        format: int32
      - name: value
        in: body
        schema:
          type: string
      - name: api-version
        in: query
        description: The requested API version
        type: string
      responses:
        200:
          description: Success
    delete:
      tags:
      - Values
      operationId: Delete
      consumes: []
      produces: []
      parameters:
      - name: id
        in: path
        required: true
        type: integer
        format: int32
      - name: api-version
        in: query
        description: The requested API version
        type: string
      responses:
        200:
          description: Success
definitions:
  Item:
    type: object
    properties:
      att1:
        format: int32
        type: integer
      att2:
        type: string

